.\" Copyright (c) 1993 Michael Haardt (u31b3hs@pool.informatik.rwth-aachen.de), Fri Apr  2 11:32:09 MET DST 1993
.\" This file may be distributed under the GNU General Public License.
.\" Modified Sat Jul 24 17:06:52 1993 by Rik Faith (faith@cs.unc.edu)
.TH INTRO 5 "24 July 1993" "Linux" "Linux Programmer's Manual"
.SH NAME
intro \- Introduction to file formats
.SH DESCRIPTION
This chapter describes various file formats and the used C structures,
if any.
.SH AUTHORS
Look at the header of the manual page for the author(s) and copyright
conditions.  Note that these can be different from page to page!
