.\" Copyright (c) 1993 Michael Haardt (u31b3hs@pool.informatik.rwth-aachen.de), Fri Apr  2 11:32:09 MET DST 1993
.\" This file may be distributed under the GNU General Public License.
.\" Modified Sat Jul 24 17:08:16 1993 by Rik Faith (faith@cs.unc.edu)
.TH MOTD 5 "December 29 1992" "Linux" "Linux Programmer's Manual"
.SH NAME
motd \- message of the day
.SH DESCRIPTION
\fB/etc/motd\fP is an ASCII file which contents are showed by login(1)
before it executes the login shell.
.SH FILES
/etc/motd
.SH "SEE ALSO"
.BR login (1)
