.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (c) 1993 Michael Haardt
.\" (u31b3hs@pool.informatik.rwth-aachen.de),
.\" Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This file may be distributed under the GNU General Public License.
.\"
.\" Modified Thu Jul 22 14:00:08 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Tue Aug 10 1993 by Alan Cox (iiitac@pyramid.swansea.ac.uk)
.\"
.TH ACCT 2 "10 August 1993" "Linux 0.99.11" "Linux Programmer's Manual"
.SH NAME
acct \- switch process accounting on or off
.SH SYNOPSIS
.ad l
.nf
.B #include <unistd.h>
.sp
.BI "int acct(const char *" filename );
.fi
.ad b
.SH DESCRIPTION
.BR WARNING :
Since this function is not implemented as of Linux 0.99.11, it will always
return \-1 and set
.I errno
to
.BR ENOSYS .
If acctkit is installed the function performs 'as
advertised'.

When called with the name of an existing file as argument, accounting is
turned on, records for each terminating process are appended to
\fIfilename\fP as it terminates.  An argument of \fBNULL\fP causes
accounting to be turned off.
.SH "RETURN VALUE"
On success, zero is returned.  On error, \-1 is returned, and
.I errno
is set appropriately.
.SH NOTES
No accounting is produced for programs running when a crash occurs.  In
particular, nonterminating processes are never accounted for.
.SH "SEE ALSO"
.BR acct (5)
