.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" Portions extracted from linux/mm/swap.c:
.\"                Copyright (C) 1991, 1992  Linus Torvalds
.\" May be distributed under the GNU General Public License
.TH IDLE 2 "24 July 1993" "Linux 0.99.11" "Linux Programmer's Manual"
.SH NAME
idle \- make process idle
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.B int idle(void);
.SH DESCRIPTION
.B idle
makes the process idle.  This really doesn't do much: it just searches for
likely candidates for swapping out or forgetting about. This speeds up the
search when we actually have to swap.
.SH "RETURN VALUE"
.B idle
always returns 0.
