.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (c) 1993 Michael Haardt
.\" (u31b3hs@pool.informatik.rwth-aachen.de)
.\" Fri Apr  2 11:32:09 MET DST 1993
.\" 
.\" This file may be distributed under the GNU General Public License.
.\"
.\" Modified Sat Jul 24 15:12:05 1993 by Rik Faith (faith@cs.unc.edu)
.\"
.TH IOPERM 2 "January 21, 1993" "Linux" "Linux Programmer's Manual"
.SH NAME
ioperm \- set port input/output permissions
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.BI "int ioperm(unsigned long " from ", unsigned long " num ", int " turn_on );
.SH DESCRIPTION
\fBIoperm\fP sets the port access permission bits for the process for
\fInum\fP bytes starting from port address \fBfrom\fP to the value
\fBturn_on\fP.  The use of \fBioperm\fP require root privileges.

Only the first 0x3ff I/O ports can be specified in this manner.  For more
ports, the
.B iopl
function must be used.
.SH "RETURN VALUE"
On success, zero is returned.  On error, \-1 is returned, and
.I errno
is set appropriately.
.SH "CONFORMING TO"
\fBioperm\fP is Linux specific.
.SH "SEE ALSO"
.BR iopl (2)
