.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.TH MOUNT 2 "23 July 1993" "Linux 0.99.11" "Linux Programmer's Manual"
.SH NAME
mount, umount \- mount and unmount filesystems.
.SH SYNOPSIS
.B #include <sys/mount.h>
.sp
.BI "int mount(const char *" specialfile ", const char * " dir
.BI ", const char * " filesystemtype ", unsigned long " rwflag
.BI ", const void * " data );
.sp
.BI "int umount(const char *" specialfile );
.SH DESCRIPTION
.B mount
attaches the filesystem specified by
.I specialfile
(which is often a device name)
to the directory specified by
.IR dir .

.B umount
removes the attachment of the filesystem specified by
.IR specialfile .

Only the super-user may mount and unmount filesystems.
.SH "RETURN VALUE"
On success, zero is returned.  On error, \-1 is returned, and
.I errno
is set appropriately.
.SH ERRORS
The errors are far too numerous to be completely list here.  Further, each
filesystem type may have its own special errors and its own special
behavior.  See the kernel source code for details.

.TP 0.8i
.B EPERM
The user is not the super-user.
.TP
.B ENODEV
.I Specialfile
is not valid.
.TP
.B ENOTBLK
.I Specialfile
is not a block device (if a device was required).
.TP
.B EACCES
Permission to read the inode is not available.
.TP
.B ENXIO
The major number of
.I specialfile
is out of range.
.TP
.B EINVAL
A parameter was invalid.
.SH "CONFORMING TO"
These function are completely Linux-specific.
.SH "SEE ALSO"
.BR mount "(8), " umount (8)
