.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (c) 1992 Drew Eckhardt (drew@cs.colorado.edu), March 28, 1992
.\" May be distributed under the GNU General Public License.
.\" Modified by Michael Haardt (u31b3hs@pool.informatik.rwth-aachen.de)
.\" Modified Sat Jul 24 12:02:47 1993 by Rik Faith (faith@cs.unc.edu)
.TH SYNC 2 "24 July 1993" "Linux" "Linux Programmer's Manual"
.SH NAME
sync \- commit buffer cache to disk.
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.B int sync(void);
.SH DESCRIPTION
.B sync
first commits inodes to buffers, and then buffers to disk.
.SH "RETURN VALUE"
.B sync
always returns 0.
.SH "CONFOMRING TO"
SVID, AT&T, X/OPEN, BSD 4.3
.SH BUGS
\fBsync()\fP only schedules the writes, so it may return before the actual
writing is done.
.SH "SEE ALSO"
.BR fsync "(2), " update "(8), " sync (8)
