.\" Copyright (c) 1993 Michael Haardt (u31b3hs@pool.informatik.rwth-aachen.de), Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\" 
.\" Modified Sat Jul 24 16:58:03 1993 by Rik Faith (faith@cs.unc.edu)
.TH LP 4 "19 December 1992" "Linux" "Linux Programmer's Manual"
.SH NAME
lp \- line printer devices
.SH DESCRIPTION
\fBLp[0-2]\fP are character devices for the parallel line printers.
.LP
They are typically created by:
.RS
.sp
mknod -m 620 /dev/lp0 c 6 0 # base address 0x03bc
.br
mknod -m 620 /dev/lp1 c 6 1 # base address 0x0378
.br
mknod -m 620 /dev/lp2 c 6 2 # base address 0x0278
.br
chown root.daemon /dev/lp*
.sp
.RE
.SH FILES
/dev/lp*
.SH "SEE ALSO"
.BR mknod "(1), " chown (1)
