.\" Copyright (c) 1993 Michael Haardt
.\" (u31b3hs@pool.informatik.rwth-aachen.de), Fri Apr 2 11:32:09 MET DST
.\" 1993
.\" This file may be distributed under the GNU General Public License.
.\" Modified by Thomas Koenig (ig25@rz.uni-karlsruhe.de) 24 Apr 1993
.\" Modified Sat Jul 24 17:28:08 1993 by Rik Faith (faith@cs.unc.edu)
.TH INTRO 7  "April 23, 1993" "Linux" "Linux Programmer's Manual"
.SH NAME
intro \- Introduction to miscellany section
.SH "DESCRIPTION"
This chapter describes miscellaneous things such as nroff macro
packages, tables, C header files, the file hierarchy, general
concepts, and other things which don't fit anywhere else.
.SH "AUTHORS"
Look at the header of the manual page for the author(s) and copyright
conditions.  Note that these can be different from page to page!
