'\" t
.\" (c) 1993 by Thomas Koenig (ig25@rz.uni-karlsruhe.de)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\" Modified Sat Jul 24 17:35:15 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Sun Feb 19 22:02:32 1995 by Rik Faith (faith@cs.unc.edu)
.TH SUFFIXES 7  "April 25, 1993" "Linux" "Linux Programmer's Manual"
.SH NAME
suffixes \- list of file suffixes
.SH DESCRIPTION
It is customary to mark the contents of a file with the file suffix,
which consists of a period, followed by one or more letters.  Many
standard utilities such as compilers use this to recognize the type of
file they are dealing with, and the make(1) utility contains many
rules for dealing with files based on suffix type.
.PP
Following is a list of suffixes which are likely to be found on a
Linux system.
.PP
.TS 
l | l
_ | _
lI |  l .
Suffix	File type
 ,v	Files for RCS (Revision Control System)
 -	backup file
 .C	C++ source code
 .F	FORTRAN source with cpp(1) directives
 .S	Assembler source with cpp(1) directives
 .Z	File compressed using compress(1)
 .[0-9]+pk	TeX font files
 .[1-9]	Manual page for the corresponding section
 .[1-9][a-z]	Manual page for section plus subsection
 .a	static object code library
 .afm	PostScript font metrics
 .arc	ARC archive
 .awk	AWK language program
 .bak	Backup file
 .bm	Bitmap source
 .c	C source
 .cat	Message catalog files
 .cf	configuration file
 .conf	configuration file
 .config	configuration file
 .cweb	Donald Knuth's WEB for C
 .dat	data file
 .def	Modula-2 source for definition modules
 .def	other definition files
 .diff	ASCII File differences
 .doc	documentation file
 .dvi	TeX device independent output
 .el	EMACS lisp source
 .elc	compiled EMACS lisp
 .eps	encapsulated postscript
 .f	FORTRAN source
 .fas	pre-compiled common Lisp
 .fi	FORTRAN include files
 .gif	Graphics Interchange Format
 .gsf	Ghostscript fonts
 .gz	File compressed using gzip(1)
 .h	C or C++ header files
 .hlp	Help file
 .i	C source after preprocessing
 .icon	Bitmap source
 .image	Bitmap source
 .in	Input file for some utility
 .info	Files for the EMACS info browser
 .jpg	JPEG compressed picture format
 .l	lex(1) or flex(1) files
 .lib	Common Lisp library
 .ln	Files for use with lint(1)
 .lsp	Common Lisp source
 .man	Manual page
 .mf	Metafont (font generator for TeX) source
 .mm	Sources for groff(1) in mm - format
 .mod	Modula-2 source for implementation modules
 .o	object file
 .old	old or backup file
 .out	Output file, often executable program (a.out)
 .p	Pascal source
 .patch	File differences from patch(1)
 .pcf	X11 font files (???)
 .pfa	Postscript font definition files
 .pid	File to store daemon pid (e.g. crond.pid)
 .pl	Perl script
 .pr	Bitmap source
 .ps	Postscript file
 .r	RATFOR source
 .rules	Rules for something
 .s	Assembler source
 .sa	Something to do with shared libraries (???)
 .sc	sc(1) spreadsheed commands
 .sh	sh(1) scripts
 .shar	archive created by the shar(1) utility
 .so	DLL dynamic library
 .sty	LaTeX style files
 .sym	Modula-2 compiled definition modules
 .tar	archive created by the tar(1) utility
 .tar.Z	tar archive compressed with compress(1)
 .tar.gz	tar archive compressed with gzip(1)
 .taz	Tar archive compressed with compress(1)
 .tex	TeX or LaTeX source
 .texi	equivalent to \fI.texinfo\fR
 .texinfo	TeXinfo documentation source
 .tfm	TeX font metrics
 .tmpl	Template files
 .tpz	Tar archive compressed with gzip(1)
 .txt	Text file
 .uue	Binary file encoded with uuencode(1)
 .web	Donald Knuth's WEB
 .y	yacc(1) or bison(1) (parser generator) files
 .z	File compressed using pack(1) (or an old gzip(1))
 .zoo	ZOO archive
 ~	EMACS or patch backup file
 rc	Startup file, e.g. .newsrc
.TE
.SH "CONFORMS TO"
General UNIX conventions
.SH BUGS
This list is not exhaustive.
.SH "SEE ALSO"
.BR file "(1), " make (1)
