.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.TH CEXP2 3 2002-07-28 "" "complex math routines"
.SH NAME
cexp2, cexp2f, cexp2l \- base-2 exponent of a complex number
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BI "double complex cexp2(double complex " z ");"
.sp
.BI "float complex cexp2f(float complex " z ");"
.sp
.BI "long double complex cexp2l(long double complex " z ");"
.sp
.SH DESCRIPTION
The function returns 2 raised to the power of z. 
.SH "CONFORMING TO"
C99
\" in "future directions" of C99
.SH "SEE ALSO"
.BR cabs (3),
.BR cexp (3),
.BR clog10 (3)