.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.TH CARG 3 2002-07-28 "" "complex math routines"
.SH NAME
cproj, cprojf, cprojl \- project into Riemann Sphere
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BR "double complex cproj(double complex " z ");"
.sp
.BR "float complex cprojf(float complex " z ");"
.sp
.BR "long double complex cprojl(long double complex " z ");"
.sp
.SH DESCRIPTION
With this function you can project a point in the plane onto the surface of a 
Riemann Sphere, the one-point compactification of the complex plane.
Each finite point z projects to z itself.
Every complex infinite values is projected to a single infinite value,
namely to positive infinity on the real axis.
.SH "CONFORMING TO"
C99
.SH "SEE ALSO"
.BR cabs (3)
