.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.TH CTANH 3 2002-07-28 "" "complex math routines"
.SH NAME
ctanh, ctanhf, ctanhl \- complex hyperbolic tangent
.SH SYNOPSIS
.B #include <complex.h>
.sp
.BR "double complex ctanh(double complex " z ");"
.sp
.BR "float complex ctanhf(float complex " z );
.sp
.BR "long double complex ctanhl(long double complex " z ");"
.sp
.SH DESCRIPTION
The complex hyperbolic tangent function tanh(z) is defined as
cosh(z)/sinh(z).
.SH "CONFORMING TO"
C99
.SH "SEE ALSO"
.BR cabs (3),
.BR ccosh (3),
.BR csinh (3)
