.\" (c) 1993 by Thomas Koenig (ig25@rz.uni-karlsruhe.de)
.\" This file can be distributed under the terms of the GNU General Public
.\" License.
.\" Modified Sat Jul 24 19:01:20 1993 by Rik Faith (faith@cs.unc.edu)
.TH LOCALECONV 3  "April 25, 1993" "GNU" "Linux Programmer's Manual"
.SH NAME
localeconv \- get numeric formatting information
.SH SYNOPSIS
.nf
.B #include <locale.h>
.sp
.B struct lconv *localeconf(void);
.fi
.SH DESCRIPTION
The
.B localeconf()
function returns a string to a
.B struct lconv
for the current locale.
.SH "CONFORMS TO"
ANSI C, POSIX.1
.SH "BUGS"
At the moment, the only supported locales are the portable
.BR """C""" " and " """POSIX"""
locales, which makes calling
.B localeconv()
almost useless.
Support for other locales will be there Real Soon Now.
.PP
The
.B printf()
family of functions may or may not honor the current locale.
.SH "SEE ALSO"
.BR locale "(1), " localedef "(1), " strcoll "(3), " isalpha (3),
.BR setlocale "(3), " strftime "(3), " locale (7)
