.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL, 2002-07-27 Walter Harms
.\"
.TH sincos 3  2002-07-27 "GNU" "Linux Programmer's Manual"
.SH NAME
sincos \- calculate sin and cos simultaneously
.SH SYNOPSIS
.nf
.B #include <math.h>
.sp
.BI "double sincos(double " x ", double *" sin ", double *" cos );
.sp
.BI "float sincosf(float " x ", float *" sin ", float *" cos );
.sp
.BI "long double sincosl(long double " x ", long double *" sin ", long double *" cos );
.fi
.SH DESCRIPTION
Several applications need sine and cosine of the same angle
.IR x .
This function computes both at the same time, and stores the results
via the given pointers.
.SH "CONFORMING TO"
This function is a GNU extension.
.SH "SEE ALSO"
.BR drem (3),
.BR sin (3),
.BR cos (3),
.BR tan (3)
