.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\" May be distributed under the GNU General Public License
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 17:55:39 1993 by Rik Faith (faith@cs.unc.edu)
.TH STRTOK 3  "April 12, 1993" "GNU" "Linux Programmer's Manual"
.SH NAME
strtok \- extract token from string
.SH SYNOPSIS
.nf
.B #include <string.h>
.sp
.BI "char *strtok(char *" s ", const char *" delim );
.fi
.SH DESCRIPTION
The \fBstrtok()\fP function breaks the string \fIs\fP into a series
of tokens delimited by \fIdelim\fP.  The first call to \fBstrtok()\fP
should have \fIs\fP as the first argument.  Subsequent calls should 
have the first argument set to NULL.  The separator string \fIdelim\fP
may be different for each call.
.PP
The first call to \fBstrtok()\fP returns the first token in \fIs\fP or
NULL if \fIdelim\fP is not found in \fIs\fP.  A pointer to the next
character is saved for the next call to \fBstrtok\fP.  Subsequent calls 
return subsequent tokens until \fPdelim\fP is no longer found, when
NULL is returned.
.SH "RETURN VALUE"
The \fBstrtok()\fP function returns a pointer to the next token, or
NULL if there are no more tokens.
.SH "CONFORMING TO"
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH "SEE ALSO"
.BR index "(3), " memchr "(3), " rindex "(3), " strchr (3),
.BR strpbrk "(3), " strsep "(3), " strspn "(3), " strstr (3)
